import React from 'react'
import { Home, Users as UsersIcon, Settings as SettingsIcon, FileText, HardHat, Construction, TrendingUp, Calendar, Camera, FolderOpen, Box, BarChart3 } from 'lucide-react'
import type { AppRoute } from './schema'

export const routes: AppRoute[] = [
  {
    path: '/inicio',
    label: 'Inicio',
    icon: <Home className="w-5 h-5" />,
    group: 'Inicio',
    meta: { resourcePath: 'inicio', hideProjectSelector: true },
    element: React.lazy(() => import('../../pages/initialpages/DashboardPage')),
  },
  {
    path: '/direccion',
    label: 'Dirección',
    icon: <BarChart3 className="w-5 h-5" />,
    group: 'Dirección',
    meta: { resourcePath: 'direccion', hideProjectSelector: true },
    element: React.lazy(() => import('../../pages/direccion/DireccionLayout')),
    children: [
      {
        path: 'reporte',
        label: 'Reporte Dirección',
        icon: <TrendingUp className="w-5 h-5" />,
        meta: { resourcePath: 'direccion.reporte', label: 'Reporte', order: 1 },
        element: React.lazy(() => import('../../pages/direccion/ReporteDireccionPage')),
      },
    ],
  },
  {
    path: '/obra',
    label: 'Administración de Obra',
    icon: <HardHat className="w-5 h-5" />,
    group: 'Operaciones',
    meta: { resourcePath: 'obra' },
    element: React.lazy(() => import('../../pages/obra/ObraLayout')),
    children: [
      {
        path: 'reglamento',
        label: 'Reglamento de Obra',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.reglamento', label: 'Reglamento', order: 0 },
        element: React.lazy(() => import('../../pages/obra/ReglamentoObraPage')),
      },
      {
        path: 'presupuesto',
        label: 'Presupuesto',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.presupuesto', label: 'Presupuesto', order: 1, requiresNotContratista: true },
        element: React.lazy(() => import('../../pages/obra/PresupuestoPage')),
      },
      {
        path: 'contratistas',
        label: 'Contratistas',
        icon: <UsersIcon className="w-5 h-5" />,
        meta: { resourcePath: 'obra.contratistas', label: 'Contratistas', order: 2 },
        element: React.lazy(() => import('../../pages/obra/ContratistasPage')),
      },
      {
        path: 'contratos',
        label: 'Contratos',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.contratos', label: 'Contratos', order: 3 },
        element: React.lazy(() => import('../../pages/obra/ContratosPage')),
      },
      {
        path: 'vigencia-contratos',
        label: 'Vigencia Contratos',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.vigencia', label: 'Vigencia', order: 4 },
        element: React.lazy(() => import('../../pages/obra/VigenciaContratosPage')),
      },
      {
        path: 'requisiciones-pago',
        label: 'Requisiciones de Pago',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.requisiciones', label: 'Requisiciones', order: 5 },
        element: React.lazy(() => import('../../pages/obra/RequisicionesPagoPage')),
      },
      {
        path: 'solicitudes-pago',
        label: 'Solicitudes de Pago',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.solicitudes', label: 'Solicitudes', order: 6 },
        element: React.lazy(() => import('../../pages/obra/SolicitudesPagoPage')),
      },
      {
        path: 'registro-pagos',
        label: 'Pagos',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.registro_pagos', label: 'Pagos', order: 7 },
        element: React.lazy(() => import('../../pages/obra/RegistroPagosPage')),
      },
      {
        path: 'estado-cuenta',
        label: 'Estado de Cuenta',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.estado_cuenta', label: 'Estado Cuenta', order: 8 },
        element: React.lazy(() => import('../../pages/obra/EstadoCuentaPage')),
      },
      {
        path: 'minutas',
        label: 'Minutas',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.minutas', label: 'Minutas', order: 9 },
        element: React.lazy(() => import('../../pages/obra/MinutasPage')),
      },
      {
        path: 'fuerzas-trabajo',
        label: 'Fuerza Laboral',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'obra.fuerzas', label: 'Fuerzas', order: 9 },
        element: React.lazy(() => import('../../pages/obra/FuerzaTrabajoPage')),
      },
    ],
  },
  {
    path: '/proyecto',
    label: 'Proyecto',
    icon: <FolderOpen className="w-5 h-5" />,
    group: 'Proyecto',
    meta: { resourcePath: 'proyecto' },
    element: React.lazy(() => import('../../pages/obra/ObraLayout')),
    children: [
      {
        path: 'info',
        label: 'Info Proyecto',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'proyecto.info', label: 'Info Proyecto', order: 0 },
        element: React.lazy(() => import('../../pages/proyecto/InfoProyectoPage')),
      },
      {
        path: 'visualizador',
        label: 'Visualizador Autodesk',
        icon: <Box className="w-5 h-5" />,
        meta: { resourcePath: 'proyecto.visualizador', label: 'Visualizador', order: 1 },
        element: React.lazy(() => import('../../pages/proyecto/VisualizadorAutodeskPage')),
      },
    ],
  },
  {
    path: '/construccion',
    label: 'Construcción',
    icon: <Construction className="w-5 h-5" />,
    group: 'Construcción',
    meta: { resourcePath: 'construccion' },
    element: React.lazy(() => import('../../pages/obra/ObraLayout')),
    children: [
      {
        path: 'avance-obra',
        label: 'Avance de Obra',
        icon: <TrendingUp className="w-5 h-5" />,
        meta: { resourcePath: 'construccion.avance', label: 'Avance de Obra', order: 0 },
        element: React.lazy(() => import('../../pages/construccion/AvanceObraPage')),
      },
      {
        path: 'programa-obra',
        label: 'Programa de Obra',
        icon: <Calendar className="w-5 h-5" />,
        meta: { resourcePath: 'construccion.programa', label: 'Programa de Obra', order: 1 },
        element: React.lazy(() => import('../../pages/construccion/ProgramaObraPage')),
      },
      {
        path: 'recorrido-360',
        label: 'Recorrido 360°',
        icon: <Camera className="w-5 h-5" />,
        meta: { resourcePath: 'construccion.recorrido', label: 'Recorrido 360°', order: 2 },
        element: React.lazy(() => import('../../pages/construccion/Recorrido360Page')),
      },
    ],
  },
  {
    path: '/configuracion',
    label: 'Configuración',
    icon: <SettingsIcon className="w-5 h-5" />,
    group: 'Administración',
    meta: { resourcePath: 'settings' },
    element: React.lazy(() => import('../../pages/configpages/ConfiguracionPlataformaPage')),
    children: [
      {
        path: 'usuarios',
        label: 'Usuarios',
        icon: <UsersIcon className="w-5 h-5" />,
        meta: { resourcePath: 'settings.users', label: 'Usuarios', order: 1 },
        element: React.lazy(() => import('../../pages/configpages/UsuariosConfigPage')),
      },
      {
        path: 'importacion',
        label: 'Importar Datos',
        icon: <FileText className="w-5 h-5" />,
        meta: { resourcePath: 'settings.import', label: 'Importar', order: 2 },
        element: React.lazy(() => import('../../pages/configpages/ImportacionDatosPage')),
      },
      {
        path: 'migrar-amortizaciones',
        label: 'Migrar Amortizaciones',
        icon: <SettingsIcon className="w-5 h-5" />,
        meta: { resourcePath: 'settings.migrate', label: 'Migración', order: 3 },
        element: React.lazy(() => import('../../pages/configpages/MigrarAmortizacionesPage')),
      },
    ],
  },
]